homeassistant:
  discovery_prefix: homeassistant

mqtt:
  host: 192.168.1.251
  port: 1883
  user: zencontrol
  password: controlzen
  keepalive: 60

zencontrol:
  - id: 1
    name: zen1
    label: Zencontrol 1
    mac: 7C:BA:CC:22:E3:4F
    host: 192.168.1.150
    port: 5108
  - id: 2
    name: zen2
    label: Zencontrol 2
    mac: 7C:BA:CC:22:E3:7A
    host: 192.168.1.193
    port: 5108
  - id: 3
    name: zen3
    label: Zencontrol 3
    mac: 7C:BA:CC:22:E3:8D
    host: 192.168.1.212
    port: 5108
